export const vaultAbi = [
  { type: "function", name: "owner", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "deployedAtBlock", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "guardian", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "policyVersion", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "lastHeartbeat", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "heartbeatInterval", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "gracePeriod", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "pendingAt", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "settled", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "vetoed", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "status", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "canOpenSettlementForPolicy", stateMutability: "view", inputs: [{ name: "expectedPolicyVersion", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "canFinalizeSettlementForPolicy", stateMutability: "view", inputs: [{ name: "expectedPolicyVersion", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "beneficiaryCount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "beneficiaryAt", stateMutability: "view", inputs: [{ name: "index", type: "uint256" }], outputs: [{ type: "address" }] },
  { type: "function", name: "shareBps", stateMutability: "view", inputs: [{ name: "beneficiary", type: "address" }], outputs: [{ type: "uint16" }] },
  { type: "function", name: "claimable", stateMutability: "view", inputs: [{ name: "beneficiary", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "heartbeat", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "vetoSettlement", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "finalizeSettlement", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "openSettlementForPolicy", stateMutability: "nonpayable", inputs: [{ name: "expectedPolicyVersion", type: "uint256" }], outputs: [] },
  { type: "function", name: "finalizeSettlementForPolicy", stateMutability: "nonpayable", inputs: [{ name: "expectedPolicyVersion", type: "uint256" }], outputs: [] },
  { type: "function", name: "claim", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "withdraw", stateMutability: "nonpayable", inputs: [{ name: "recipient", type: "address" }, { name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "updatePolicy", stateMutability: "nonpayable", inputs: [{ name: "guardian", type: "address" }, { name: "beneficiaries", type: "address[]" }, { name: "shares", type: "uint16[]" }, { name: "heartbeatInterval", type: "uint256" }, { name: "gracePeriod", type: "uint256" }, { name: "testnetDemo", type: "bool" }], outputs: [] },
  { type: "event", name: "Deposit", inputs: [{ indexed: true, name: "sender", type: "address" }, { indexed: false, name: "amount", type: "uint256" }] },
  { type: "event", name: "Heartbeat", inputs: [{ indexed: true, name: "owner", type: "address" }, { indexed: true, name: "policyVersion", type: "uint256" }, { indexed: false, name: "timestamp", type: "uint256" }] },
  { type: "event", name: "PolicyUpdated", inputs: [{ indexed: true, name: "policyVersion", type: "uint256" }, { indexed: true, name: "guardian", type: "address" }, { indexed: true, name: "actor", type: "address" }, { indexed: false, name: "heartbeatInterval", type: "uint256" }, { indexed: false, name: "gracePeriod", type: "uint256" }, { indexed: false, name: "beneficiaries", type: "address[]" }, { indexed: false, name: "shares", type: "uint16[]" }] },
  { type: "event", name: "SettlementOpened", inputs: [{ indexed: true, name: "policyVersion", type: "uint256" }, { indexed: false, name: "pendingAt", type: "uint256" }, { indexed: true, name: "caller", type: "address" }] },
  { type: "event", name: "SettlementVetoedByGuardian", inputs: [{ indexed: true, name: "policyVersion", type: "uint256" }, { indexed: true, name: "guardian", type: "address" }] },
  { type: "event", name: "SettlementFinalized", inputs: [{ indexed: true, name: "policyVersion", type: "uint256" }, { indexed: false, name: "balance", type: "uint256" }, { indexed: true, name: "caller", type: "address" }] },
  { type: "event", name: "Withdrawal", inputs: [{ indexed: true, name: "recipient", type: "address" }, { indexed: false, name: "amount", type: "uint256" }, { indexed: true, name: "actor", type: "address" }] },
  { type: "event", name: "Claimed", inputs: [{ indexed: true, name: "beneficiary", type: "address" }, { indexed: false, name: "amount", type: "uint256" }] },
] as const;

export const factoryAbi = [
  { type: "function", name: "vaultOf", stateMutability: "view", inputs: [{ name: "owner", type: "address" }], outputs: [{ name: "vault", type: "address" }] },
  { type: "function", name: "createVault", stateMutability: "nonpayable", inputs: [{ name: "guardian", type: "address" }, { name: "beneficiaries", type: "address[]" }, { name: "shares", type: "uint16[]" }, { name: "heartbeatInterval", type: "uint256" }, { name: "gracePeriod", type: "uint256" }, { name: "testnetDemo", type: "bool" }], outputs: [{ name: "vault", type: "address" }] },
  { type: "event", name: "VaultCreated", inputs: [{ indexed: true, name: "owner", type: "address" }, { indexed: true, name: "vault", type: "address" }, { indexed: false, name: "testnetDemo", type: "bool" }] },
] as const;
